version: '3.9'

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - mock
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./web:/app
      - /app/node_modules

  mock:
    build: ./mock
    ports:
      - "5000:5000"
    volumes:
      - ./mock:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=SFgenAI_db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: SFgenAI_db
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
