name: Run Jest Tests
on:
  push:
    branches-ignore:
      - main
      - develop
  pull_request:
    branches-ignore:
      - main
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.15.0
          cache: 'yarn'
          cache-dependency-path: front/web/yarn.lock
      - name: Install dependencies
        run: yarn install
        working-directory: front/web
      - name: Run tests
        run: yarn test
        working-directory: front/web
