name: Restrict main merges
on:
  pull_request:
    branches:
      - main
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        run: |
          echo "Source base branch: ${{ github.base_ref }}"
          echo "Source head branch: ${{ github.head_ref }}"
          if [ "${{ github.base_ref }}" == "main" ]; then
            if [ "${{ github.head_ref }}" != "develop" ]; then
              echo "Only develop branch can be merged into main!"
              exit 1
            fi
          fi
